<?php

use App\Language;
use Illuminate\Database\Seeder;
use App\Country;
use App\CountryTranslation;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $countries = [
            ['id' => '1', 'country_code' => 'AF', 'name' => 'Afghanistan', 'code' => '93'],
            ['id' => '2', 'country_code' => 'AL', 'name' => 'Albania', 'code' => '355'],
            ['id' => '3', 'country_code' => 'DZ', 'name' => 'Algeria', 'code' => '213'],
            ['id' => '4', 'country_code' => 'AS', 'name' => 'American Samoa', 'code' => '1684'],
            ['id' => '5', 'country_code' => 'AD', 'name' => 'Andorra', 'code' => '376'],
            ['id' => '6', 'country_code' => 'AO', 'name' => 'Angola', 'code' => '244'],
            ['id' => '7', 'country_code' => 'AI', 'name' => 'Anguilla', 'code' => '1264'],
            ['id' => '8', 'country_code' => 'AQ', 'name' => 'Antarctica', 'code' => '0'],
            ['id' => '9', 'country_code' => 'AG', 'name' => 'Antigua And Barbuda', 'code' => '1268'],
            ['id' => '10', 'country_code' => 'AR', 'name' => 'Argentina', 'code' => '54'],
            ['id' => '11', 'country_code' => 'AM', 'name' => 'Armenia', 'code' => '374'],
            ['id' => '12', 'country_code' => 'AW', 'name' => 'Aruba', 'code' => '297'],
            ['id' => '13', 'country_code' => 'AU', 'name' => 'Australia', 'code' => '61'],
            ['id' => '14', 'country_code' => 'AT', 'name' => 'Austria', 'code' => '43'],
            ['id' => '15', 'country_code' => 'AZ', 'name' => 'Azerbaijan', 'code' => '994'],
            ['id' => '16', 'country_code' => 'BS', 'name' => 'Bahamas The', 'code' => '1242'],
            ['id' => '17', 'country_code' => 'BH', 'name' => 'Bahrain', 'code' => '973'],
            ['id' => '18', 'country_code' => 'BD', 'name' => 'Bangladesh', 'code' => '880'],
            ['id' => '19', 'country_code' => 'BB', 'name' => 'Barbados', 'code' => '1246'],
            ['id' => '20', 'country_code' => 'BY', 'name' => 'Belarus', 'code' => '375'],
            ['id' => '21', 'country_code' => 'BE', 'name' => 'Belgium', 'code' => '32'],
            ['id' => '22', 'country_code' => 'BZ', 'name' => 'Belize', 'code' => '501'],
            ['id' => '23', 'country_code' => 'BJ', 'name' => 'Benin', 'code' => '229'],
            ['id' => '24', 'country_code' => 'BM', 'name' => 'Bermuda', 'code' => '1441'],
            ['id' => '25', 'country_code' => 'BT', 'name' => 'Bhutan', 'code' => '975'],
            ['id' => '26', 'country_code' => 'BO', 'name' => 'Bolivia', 'code' => '591'],
            ['id' => '27', 'country_code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'code' => '387'],
            ['id' => '28', 'country_code' => 'BW', 'name' => 'Botswana', 'code' => '267'],
            ['id' => '29', 'country_code' => 'BV', 'name' => 'Bouvet Island', 'code' => '0'],
            ['id' => '30', 'country_code' => 'BR', 'name' => 'Brazil', 'code' => '55'],
            ['id' => '31', 'country_code' => 'IO', 'name' => 'British Indian Ocean Territory', 'code' => '246'],
            ['id' => '32', 'country_code' => 'BN', 'name' => 'Brunei', 'code' => '673'],
            ['id' => '33', 'country_code' => 'BG', 'name' => 'Bulgaria', 'code' => '359'],
            ['id' => '34', 'country_code' => 'BF', 'name' => 'Burkina Faso', 'code' => '226'],
            ['id' => '35', 'country_code' => 'BI', 'name' => 'Burundi', 'code' => '257'],
            ['id' => '36', 'country_code' => 'KH', 'name' => 'Cambodia', 'code' => '855'],
            ['id' => '37', 'country_code' => 'CM', 'name' => 'Cameroon', 'code' => '237'],
            ['id' => '38', 'country_code' => 'CA', 'name' => 'Canada', 'code' => '1'],
            ['id' => '39', 'country_code' => 'CV', 'name' => 'Cape Verde', 'code' => '238'],
            ['id' => '40', 'country_code' => 'KY', 'name' => 'Cayman Islands', 'code' => '1345'],
            ['id' => '41', 'country_code' => 'CF', 'name' => 'Central African Republic', 'code' => '236'],
            ['id' => '42', 'country_code' => 'TD', 'name' => 'Chad', 'code' => '235'],
            ['id' => '43', 'country_code' => 'CL', 'name' => 'Chile', 'code' => '56'],
            ['id' => '44', 'country_code' => 'CN', 'name' => 'China', 'code' => '86'],
            ['id' => '45', 'country_code' => 'CX', 'name' => 'Christmas Island', 'code' => '61'],
            ['id' => '46', 'country_code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'code' => '672'],
            ['id' => '47', 'country_code' => 'CO', 'name' => 'Colombia', 'code' => '57'],
            ['id' => '48', 'country_code' => 'KM', 'name' => 'Comoros', 'code' => '269'],
            ['id' => '49', 'country_code' => 'CG', 'name' => 'Republic Of The Congo', 'code' => '242'],
            ['id' => '50', 'country_code' => 'CD', 'name' => 'Democratic Republic Of The Congo', 'code' => '242'],
            ['id' => '51', 'country_code' => 'CK', 'name' => 'Cook Islands', 'code' => '682'],
            ['id' => '52', 'country_code' => 'CR', 'name' => 'Costa Rica', 'code' => '506'],
            ['id' => '53', 'country_code' => 'CI', 'name' => 'Cote D\'Ivoire (Ivory Coast)', 'code' => '225'],
            ['id' => '54', 'country_code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'code' => '385'],
            ['id' => '55', 'country_code' => 'CU', 'name' => 'Cuba', 'code' => '53'],
            ['id' => '56', 'country_code' => 'CY', 'name' => 'Cyprus', 'code' => '357'],
            ['id' => '57', 'country_code' => 'CZ', 'name' => 'Czech Republic', 'code' => '420'],
            ['id' => '58', 'country_code' => 'DK', 'name' => 'Denmark', 'code' => '45'],
            ['id' => '59', 'country_code' => 'DJ', 'name' => 'Djibouti', 'code' => '253'],
            ['id' => '60', 'country_code' => 'DM', 'name' => 'Dominica', 'code' => '1767'],
            ['id' => '61', 'country_code' => 'DO', 'name' => 'Dominican Republic', 'code' => '1809'],
            ['id' => '62', 'country_code' => 'TP', 'name' => 'East Timor', 'code' => '670'],
            ['id' => '63', 'country_code' => 'EC', 'name' => 'Ecuador', 'code' => '593'],
            ['id' => '64', 'country_code' => 'EG', 'name' => 'Egypt', 'code' => '20'],
            ['id' => '65', 'country_code' => 'SV', 'name' => 'El Salvador', 'code' => '503'],
            ['id' => '66', 'country_code' => 'GQ', 'name' => 'Equatorial Guinea', 'code' => '240'],
            ['id' => '67', 'country_code' => 'ER', 'name' => 'Eritrea', 'code' => '291'],
            ['id' => '68', 'country_code' => 'EE', 'name' => 'Estonia', 'code' => '372'],
            ['id' => '69', 'country_code' => 'ET', 'name' => 'Ethiopia', 'code' => '251'],
            ['id' => '70', 'country_code' => 'XA', 'name' => 'External Territories of Australia', 'code' => '61'],
            ['id' => '71', 'country_code' => 'FK', 'name' => 'Falkland Islands', 'code' => '500'],
            ['id' => '72', 'country_code' => 'FO', 'name' => 'Faroe Islands', 'code' => '298'],
            ['id' => '73', 'country_code' => 'FJ', 'name' => 'Fiji Islands', 'code' => '679'],
            ['id' => '74', 'country_code' => 'FI', 'name' => 'Finland', 'code' => '358'],
            ['id' => '75', 'country_code' => 'FR', 'name' => 'France', 'code' => '33'],
            ['id' => '76', 'country_code' => 'GF', 'name' => 'French Guiana', 'code' => '594'],
            ['id' => '77', 'country_code' => 'PF', 'name' => 'French Polynesia', 'code' => '689'],
            ['id' => '78', 'country_code' => 'TF', 'name' => 'French Southern Territories', 'code' => '0'],
            ['id' => '79', 'country_code' => 'GA', 'name' => 'Gabon', 'code' => '241'],
            ['id' => '80', 'country_code' => 'GM', 'name' => 'Gambia The', 'code' => '220'],
            ['id' => '81', 'country_code' => 'GE', 'name' => 'Georgia', 'code' => '995'],
            ['id' => '82', 'country_code' => 'DE', 'name' => 'Germany', 'code' => '49'],
            ['id' => '83', 'country_code' => 'GH', 'name' => 'Ghana', 'code' => '233'],
            ['id' => '84', 'country_code' => 'GI', 'name' => 'Gibraltar', 'code' => '350'],
            ['id' => '85', 'country_code' => 'GR', 'name' => 'Greece', 'code' => '30'],
            ['id' => '86', 'country_code' => 'GL', 'name' => 'Greenland', 'code' => '299'],
            ['id' => '87', 'country_code' => 'GD', 'name' => 'Grenada', 'code' => '1473'],
            ['id' => '88', 'country_code' => 'GP', 'name' => 'Guadeloupe', 'code' => '590'],
            ['id' => '89', 'country_code' => 'GU', 'name' => 'Guam', 'code' => '1671'],
            ['id' => '90', 'country_code' => 'GT', 'name' => 'Guatemala', 'code' => '502'],
            ['id' => '91', 'country_code' => 'XU', 'name' => 'Guernsey and Alderney', 'code' => '44'],
            ['id' => '92', 'country_code' => 'GN', 'name' => 'Guinea', 'code' => '224'],
            ['id' => '93', 'country_code' => 'GW', 'name' => 'Guinea-Bissau', 'code' => '245'],
            ['id' => '94', 'country_code' => 'GY', 'name' => 'Guyana', 'code' => '592'],
            ['id' => '95', 'country_code' => 'HT', 'name' => 'Haiti', 'code' => '509'],
            ['id' => '96', 'country_code' => 'HM', 'name' => 'Heard and McDonald Islands', 'code' => '0'],
            ['id' => '97', 'country_code' => 'HN', 'name' => 'Honduras', 'code' => '504'],
            ['id' => '98', 'country_code' => 'HK', 'name' => 'Hong Kong S.A.R.', 'code' => '852'],
            ['id' => '99', 'country_code' => 'HU', 'name' => 'Hungary', 'code' => '36'],
            ['id' => '100', 'country_code' => 'IS', 'name' => 'Iceland', 'code' => '354'],
            ['id' => '101', 'country_code' => 'IN', 'name' => 'India', 'code' => '91'],
            ['id' => '102', 'country_code' => 'ID', 'name' => 'Indonesia', 'code' => '62'],
            ['id' => '103', 'country_code' => 'IR', 'name' => 'Iran', 'code' => '98'],
            ['id' => '104', 'country_code' => 'IQ', 'name' => 'Iraq', 'code' => '964'],
            ['id' => '105', 'country_code' => 'IE', 'name' => 'Ireland', 'code' => '353'],
            ['id' => '106', 'country_code' => 'IL', 'name' => 'Israel', 'code' => '972'],
            ['id' => '107', 'country_code' => 'IT', 'name' => 'Italy', 'code' => '39'],
            ['id' => '108', 'country_code' => 'JM', 'name' => 'Jamaica', 'code' => '1876'],
            ['id' => '109', 'country_code' => 'JP', 'name' => 'Japan', 'code' => '81'],
            ['id' => '110', 'country_code' => 'XJ', 'name' => 'Jersey', 'code' => '44'],
            ['id' => '111', 'country_code' => 'JO', 'name' => 'Jordan', 'code' => '962'],
            ['id' => '112', 'country_code' => 'KZ', 'name' => 'Kazakhstan', 'code' => '7'],
            ['id' => '113', 'country_code' => 'KE', 'name' => 'Kenya', 'code' => '254'],
            ['id' => '114', 'country_code' => 'KI', 'name' => 'Kiribati', 'code' => '686'],
            ['id' => '115', 'country_code' => 'KP', 'name' => 'Korea North', 'code' => '850'],
            ['id' => '116', 'country_code' => 'KR', 'name' => 'Korea South', 'code' => '82'],
            ['id' => '117', 'country_code' => 'KW', 'name' => 'Kuwait', 'code' => '965'],
            ['id' => '118', 'country_code' => 'KG', 'name' => 'Kyrgyzstan', 'code' => '996'],
            ['id' => '119', 'country_code' => 'LA', 'name' => 'Laos', 'code' => '856'],
            ['id' => '120', 'country_code' => 'LV', 'name' => 'Latvia', 'code' => '371'],
            ['id' => '121', 'country_code' => 'LB', 'name' => 'Lebanon', 'code' => '961'],
            ['id' => '122', 'country_code' => 'LS', 'name' => 'Lesotho', 'code' => '266'],
            ['id' => '123', 'country_code' => 'LR', 'name' => 'Liberia', 'code' => '231'],
            ['id' => '124', 'country_code' => 'LY', 'name' => 'Libya', 'code' => '218'],
            ['id' => '125', 'country_code' => 'LI', 'name' => 'Liechtenstein', 'code' => '423'],
            ['id' => '126', 'country_code' => 'LT', 'name' => 'Lithuania', 'code' => '370'],
            ['id' => '127', 'country_code' => 'LU', 'name' => 'Luxembourg', 'code' => '352'],
            ['id' => '128', 'country_code' => 'MO', 'name' => 'Macau S.A.R.', 'code' => '853'],
            ['id' => '129', 'country_code' => 'MK', 'name' => 'Macedonia', 'code' => '389'],
            ['id' => '130', 'country_code' => 'MG', 'name' => 'Madagascar', 'code' => '261'],
            ['id' => '131', 'country_code' => 'MW', 'name' => 'Malawi', 'code' => '265'],
            ['id' => '132', 'country_code' => 'MY', 'name' => 'Malaysia', 'code' => '60'],
            ['id' => '133', 'country_code' => 'MV', 'name' => 'Maldives', 'code' => '960'],
            ['id' => '134', 'country_code' => 'ML', 'name' => 'Mali', 'code' => '223'],
            ['id' => '135', 'country_code' => 'MT', 'name' => 'Malta', 'code' => '356'],
            ['id' => '136', 'country_code' => 'XM', 'name' => 'Man (Isle of)', 'code' => '44'],
            ['id' => '137', 'country_code' => 'MH', 'name' => 'Marshall Islands', 'code' => '692'],
            ['id' => '138', 'country_code' => 'MQ', 'name' => 'Martinique', 'code' => '596'],
            ['id' => '139', 'country_code' => 'MR', 'name' => 'Mauritania', 'code' => '222'],
            ['id' => '140', 'country_code' => 'MU', 'name' => 'Mauritius', 'code' => '230'],
            ['id' => '141', 'country_code' => 'YT', 'name' => 'Mayotte', 'code' => '269'],
            ['id' => '142', 'country_code' => 'MX', 'name' => 'Mexico', 'code' => '52'],
            ['id' => '143', 'country_code' => 'FM', 'name' => 'Micronesia', 'code' => '691'],
            ['id' => '144', 'country_code' => 'MD', 'name' => 'Moldova', 'code' => '373'],
            ['id' => '145', 'country_code' => 'MC', 'name' => 'Monaco', 'code' => '377'],
            ['id' => '146', 'country_code' => 'MN', 'name' => 'Mongolia', 'code' => '976'],
            ['id' => '147', 'country_code' => 'MS', 'name' => 'Montserrat', 'code' => '1664'],
            ['id' => '148', 'country_code' => 'MA', 'name' => 'Morocco', 'code' => '212'],
            ['id' => '149', 'country_code' => 'MZ', 'name' => 'Mozambique', 'code' => '258'],
            ['id' => '150', 'country_code' => 'MM', 'name' => 'Myanmar', 'code' => '95'],
            ['id' => '151', 'country_code' => 'NA', 'name' => 'Namibia', 'code' => '264'],
            ['id' => '152', 'country_code' => 'NR', 'name' => 'Nauru', 'code' => '674'],
            ['id' => '153', 'country_code' => 'NP', 'name' => 'Nepal', 'code' => '977'],
            ['id' => '154', 'country_code' => 'AN', 'name' => 'Netherlands Antilles', 'code' => '599'],
            ['id' => '155', 'country_code' => 'NL', 'name' => 'Netherlands The', 'code' => '31'],
            ['id' => '156', 'country_code' => 'NC', 'name' => 'New Caledonia', 'code' => '687'],
            ['id' => '157', 'country_code' => 'NZ', 'name' => 'New Zealand', 'code' => '64'],
            ['id' => '158', 'country_code' => 'NI', 'name' => 'Nicaragua', 'code' => '505'],
            ['id' => '159', 'country_code' => 'NE', 'name' => 'Niger', 'code' => '227'],
            ['id' => '160', 'country_code' => 'NG', 'name' => 'Nigeria', 'code' => '234'],
            ['id' => '161', 'country_code' => 'NU', 'name' => 'Niue', 'code' => '683'],
            ['id' => '162', 'country_code' => 'NF', 'name' => 'Norfolk Island', 'code' => '672'],
            ['id' => '163', 'country_code' => 'MP', 'name' => 'Northern Mariana Islands', 'code' => '1670'],
            ['id' => '164', 'country_code' => 'NO', 'name' => 'Norway', 'code' => '47'],
            ['id' => '165', 'country_code' => 'OM', 'name' => 'Oman', 'code' => '968'],
            ['id' => '166', 'country_code' => 'PK', 'name' => 'Pakistan', 'code' => '92'],
            ['id' => '167', 'country_code' => 'PW', 'name' => 'Palau', 'code' => '680'],
            ['id' => '168', 'country_code' => 'PS', 'name' => 'Palestinian Territory Occupied', 'code' => '970'],
            ['id' => '169', 'country_code' => 'PA', 'name' => 'Panama', 'code' => '507'],
            ['id' => '170', 'country_code' => 'PG', 'name' => 'Papua new Guinea', 'code' => '675'],
            ['id' => '171', 'country_code' => 'PY', 'name' => 'Paraguay', 'code' => '595'],
            ['id' => '172', 'country_code' => 'PE', 'name' => 'Peru', 'code' => '51'],
            ['id' => '173', 'country_code' => 'PH', 'name' => 'Philippines', 'code' => '63'],
            ['id' => '174', 'country_code' => 'PN', 'name' => 'Pitcairn Island', 'code' => '0'],
            ['id' => '175', 'country_code' => 'PL', 'name' => 'Poland', 'code' => '48'],
            ['id' => '176', 'country_code' => 'PT', 'name' => 'Portugal', 'code' => '351'],
            ['id' => '177', 'country_code' => 'PR', 'name' => 'Puerto Rico', 'code' => '1787'],
            ['id' => '178', 'country_code' => 'QA', 'name' => 'Qatar', 'code' => '974'],
            ['id' => '179', 'country_code' => 'RE', 'name' => 'Reunion', 'code' => '262'],
            ['id' => '180', 'country_code' => 'RO', 'name' => 'Romania', 'code' => '40'],
            ['id' => '181', 'country_code' => 'RU', 'name' => 'Russia', 'code' => '70'],
            ['id' => '182', 'country_code' => 'RW', 'name' => 'Rwanda', 'code' => '250'],
            ['id' => '183', 'country_code' => 'SH', 'name' => 'Saint Helena', 'code' => '290'],
            ['id' => '184', 'country_code' => 'KN', 'name' => 'Saint Kitts And Nevis', 'code' => '1869'],
            ['id' => '185', 'country_code' => 'LC', 'name' => 'Saint Lucia', 'code' => '1758'],
            ['id' => '186', 'country_code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'code' => '508'],
            ['id' => '187', 'country_code' => 'VC', 'name' => 'Saint Vincent And The Grenadines', 'code' => '1784'],
            ['id' => '188', 'country_code' => 'WS', 'name' => 'Samoa', 'code' => '684'],
            ['id' => '189', 'country_code' => 'SM', 'name' => 'San Marino', 'code' => '378'],
            ['id' => '190', 'country_code' => 'ST', 'name' => 'Sao Tome and Principe', 'code' => '239'],
            ['id' => '191', 'country_code' => 'SA', 'name' => 'Saudi Arabia', 'code' => '966'],
            ['id' => '192', 'country_code' => 'SN', 'name' => 'Senegal', 'code' => '221'],
            ['id' => '193', 'country_code' => 'RS', 'name' => 'Serbia', 'code' => '381'],
            ['id' => '194', 'country_code' => 'SC', 'name' => 'Seychelles', 'code' => '248'],
            ['id' => '195', 'country_code' => 'SL', 'name' => 'Sierra Leone', 'code' => '232'],
            ['id' => '196', 'country_code' => 'SG', 'name' => 'Singapore', 'code' => '65'],
            ['id' => '197', 'country_code' => 'SK', 'name' => 'Slovakia', 'code' => '421'],
            ['id' => '198', 'country_code' => 'SI', 'name' => 'Slovenia', 'code' => '386'],
            ['id' => '199', 'country_code' => 'XG', 'name' => 'Smaller Territories of the UK', 'code' => '44'],
            ['id' => '200', 'country_code' => 'SB', 'name' => 'Solomon Islands', 'code' => '677'],
            ['id' => '201', 'country_code' => 'SO', 'name' => 'Somalia', 'code' => '252'],
            ['id' => '202', 'country_code' => 'ZA', 'name' => 'South Africa', 'code' => '27'],
            ['id' => '203', 'country_code' => 'GS', 'name' => 'South Georgia', 'code' => '0'],
            ['id' => '204', 'country_code' => 'SS', 'name' => 'South Sudan', 'code' => '211'],
            ['id' => '205', 'country_code' => 'ES', 'name' => 'Spain', 'code' => '34'],
            ['id' => '206', 'country_code' => 'LK', 'name' => 'Sri Lanka', 'code' => '94'],
            ['id' => '207', 'country_code' => 'SD', 'name' => 'Sudan', 'code' => '249'],
            ['id' => '208', 'country_code' => 'SR', 'name' => 'Suriname', 'code' => '597'],
            ['id' => '209', 'country_code' => 'SJ', 'name' => 'Svalbard And Jan Mayen Islands', 'code' => '47'],
            ['id' => '210', 'country_code' => 'SZ', 'name' => 'Swaziland', 'code' => '268'],
            ['id' => '211', 'country_code' => 'SE', 'name' => 'Sweden', 'code' => '46'],
            ['id' => '212', 'country_code' => 'CH', 'name' => 'Switzerland', 'code' => '41'],
            ['id' => '213', 'country_code' => 'SY', 'name' => 'Syria', 'code' => '963'],
            ['id' => '214', 'country_code' => 'TW', 'name' => 'Taiwan', 'code' => '886'],
            ['id' => '215', 'country_code' => 'TJ', 'name' => 'Tajikistan', 'code' => '992'],
            ['id' => '216', 'country_code' => 'TZ', 'name' => 'Tanzania', 'code' => '255'],
            ['id' => '217', 'country_code' => 'TH', 'name' => 'Thailand', 'code' => '66'],
            ['id' => '218', 'country_code' => 'TG', 'name' => 'Togo', 'code' => '228'],
            ['id' => '219', 'country_code' => 'TK', 'name' => 'Tokelau', 'code' => '690'],
            ['id' => '220', 'country_code' => 'TO', 'name' => 'Tonga', 'code' => '676'],
            ['id' => '221', 'country_code' => 'TT', 'name' => 'Trinidad And Tobago', 'code' => '1868'],
            ['id' => '222', 'country_code' => 'TN', 'name' => 'Tunisia', 'code' => '216'],
            ['id' => '223', 'country_code' => 'TR', 'name' => 'Turkey', 'code' => '90'],
            ['id' => '224', 'country_code' => 'TM', 'name' => 'Turkmenistan', 'code' => '7370'],
            ['id' => '225', 'country_code' => 'TC', 'name' => 'Turks And Caicos Islands', 'code' => '1649'],
            ['id' => '226', 'country_code' => 'TV', 'name' => 'Tuvalu', 'code' => '688'],
            ['id' => '227', 'country_code' => 'UG', 'name' => 'Uganda', 'code' => '256'],
            ['id' => '228', 'country_code' => 'UA', 'name' => 'Ukraine', 'code' => '380'],
            ['id' => '229', 'country_code' => 'AE', 'name' => 'United Arab Emirates', 'code' => '971'],
            ['id' => '230', 'country_code' => 'GB', 'name' => 'United Kingdom', 'code' => '44'],
            ['id' => '231', 'country_code' => 'US', 'name' => 'United States', 'code' => '1'],
            ['id' => '232', 'country_code' => 'UM', 'name' => 'United States Minor Outlying Islands', 'code' => '1'],
            ['id' => '233', 'country_code' => 'UY', 'name' => 'Uruguay', 'code' => '598'],
            ['id' => '234', 'country_code' => 'UZ', 'name' => 'Uzbekistan', 'code' => '998'],
            ['id' => '235', 'country_code' => 'VU', 'name' => 'Vanuatu', 'code' => '678'],
            ['id' => '236', 'country_code' => 'VA', 'name' => 'Vatican City State (Holy See)', 'code' => '39'],
            ['id' => '237', 'country_code' => 'VE', 'name' => 'Venezuela', 'code' => '58'],
            ['id' => '238', 'country_code' => 'VN', 'name' => 'Vietnam', 'code' => '84'],
            ['id' => '239', 'country_code' => 'VG', 'name' => 'Virgin Islands (British)', 'code' => '1284'],
            ['id' => '240', 'country_code' => 'VI', 'name' => 'Virgin Islands (US)', 'code' => '1340'],
            ['id' => '241', 'country_code' => 'WF', 'name' => 'Wallis And Futuna Islands', 'code' => '681'],
            ['id' => '242', 'country_code' => 'EH', 'name' => 'Western Sahara', 'code' => '212'],
            ['id' => '243', 'country_code' => 'YE', 'name' => 'Yemen', 'code' => '967'],
            ['id' => '244', 'country_code' => 'YU', 'name' => 'Yugoslavia', 'code' => '38'],
            ['id' => '245', 'country_code' => 'ZM', 'name' => 'Zambia', 'code' => '260'],
            ['id' => '246', 'country_code' => 'ZW', 'name' => 'Zimbabwe', 'code' => '263'],
        ];

        $languages = Language::all();

        foreach($countries as $key => $country){
            $country_1 = new Country();
            $country_1->code = $country['code'];
            $country_1->country_code = $country['country_code'];
            $country_1->country_order = $key;
            $country_1->save();

            foreach($languages as $language){
                $country_translations = new CountryTranslation();
                $country_translations->country_id = $country_1->id;
                $country_translations->name = $country['name'];
                $country_translations->locale = $language->language_code;
                $country_translations->save();
            }
        }

    }
}
